apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Deployment.Name }}
  labels:
    app: {{ .Values.Deployment.Label }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.Pod.Label }}
  template:
    metadata:
      labels:
        app: {{ .Values.Pod.Label }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: contain
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
