apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-manager-binding   # Name of the RoleBinding
  namespace: default                 # Namespace where the RoleBinding is applied
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}               # The ServiceAccount to bind the Role to
    namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Values.Role.name }}          # The name of the Role to reference
  apiGroup: rbac.authorization.k8s.io
